---
title: "Gbocho Alexandre "
---

# Applied Mathematician and martial artist. 

📍 **Berlin, Germany**

I am specialized in Mathematical Optimization and Control. 
I cultivated an interest in interdisciplinary work where advanced Mathematical tools and techniques are required. 
From Process Engineering, Robotics, Biotechnology (in particular, biofuels and biogazs). 

My mission, is to create tools that help engineers and scientist to build better models. 

Beside this, I am a martial artist. I have competed in several tournament in Muay Thai over the years. 
I decided to go out of retirement and went back to fighting. I am currently practicing Karate Kyokushin alongside my work. 

In 2026, I decided to get out of my comfort zone and expose myself and my work to the public.
I am aiming to build a community on Discord, Instagram and tiktok of student athlete, scientists doing sport alongside their research and people that just want to experience and learn more in different scientific fields. 

You can follow my journey on Instagram. 



[▶️ View all repositories](https://github.com/AlexN7-Shepard?tab=repositories)
